[package]
name = "mazzaroth-wasm"
version = "0.1.0"
authors = ["jeffsimpson <jsimpson@kochava.com>"]

[dependencies]
mazzaroth-wasm-derive = { path = "mazzaroth-wasm-derive" }
mazzaroth-xdr = { git = "ssh://git@github.com/kochavalabs/mazzaroth-xdr.git" }
sha3 = "0.8.1"
cfg-if = "0.1.3"
wasm-bindgen = "0.2.20"
ex-dee = { git = "ssh://git@github.com/kochavalabs/ex-dee.git" }
