[package]
name = "mazzaroth-rs"
version = "0.1.0"
authors = ["jeffsimpson <jsimpson@kochava.com>"]

[dependencies]
mazzaroth-rs-derive = { path = "mazzaroth-rs-derive" }
mazzaroth-xdr = { git = "ssh://git@github.com/kochavalabs/mazzaroth-xdr.git", branch = "develop" }
sha3 = "0.8.1"
cfg-if = "0.1.3"
wasm-bindgen = "0.2.20"
xdr-rs-serialize = { git = "ssh://git@github.com/kochavalabs/xdr-rs-serialize.git", branch = "develop" }

[features]
host-mock = []
