[package]
name = "mazzaroth-wasm-derive"
version = "0.1.0"
authors = ["jeffsimpson <jsimpson@kochava.com>"]

[dependencies]
syn = { version = "0.15.12" , features = ["full"] }
quote = "0.6.8"
proc-macro2 = "0.4"

[lib]
name = "mazzaroth_wasm_derive"
proc-macro = true